### ISSUE TITLE
Snippets: Limited functionality when using partial rendering & AJAX

### ISSUE THREAD

**Issue by juniwalk** [nette/application#123]
When partial rendering is used and you want to redraw one part of the control when signal using AJAX is invoked, no payload is sent over the network.

As @paveljanda mentioned in ublaboo/datagrid#63 the problem is in [`UIRuntime:50`](https://github.com/nette/application/blob/master/src/Bridges/ApplicationLatte/UIRuntime.php#L50) (only the main `render` method is called).

Is it prossible to add functionality to render rest of the `render` methods when redrawing? You can check the [demo code](https://github.com/juniwalk/ubergrid) (mainly the signal methods with comments).

**Comment by paveljanda** [comment]
:+1:

**Comment by matej21** [comment]
This is known limitation. You should use subcomponents instead

**Comment by juniwalk** [comment]
I need to expose this partial rendering to the user, if it was internally (in component) only then this would not be problem.

**Comment by matej21** [comment]
Partial rendering (as well as render method parameters) is only `{control}` macro feature and AFAIK it is not reflected in any other part of nette/application. Personally, I think partial rendering should be removed :)

**Comment by paveljanda** [comment]
You got a point though I would not remove it.

**Comment by juniwalk** [comment]
It is great feature to render parts of the control in different places and not as a whole block.

**Comment by hrach** [comment]
Such usecase should be possible to resolve by using snippetArea.

**Comment by juniwalk** [comment]
@hrach Even when I am not actually including the template? And how would I use it if [this](https://github.com/juniwalk/ubergrid/blob/master/src/templates/uberGrid.latte) would be in presenter? (For example I wanted to print the grid differently)

The reason for all this is that the template for the datagrid can (and will) be very hard to modify and this can help us render the control in different ways without the need to modify that large template.

**Comment by hrach** [comment]
@juniwalk you will have to wrap up your partial rended calls and invalidate the snippetArea. In that case the template will be processed and partial renders used, however, only thier snippet results will be send back.

**Comment by juniwalk** [comment]
@hrach Looks good, so if I use partial rendering of the demo control in presenter, I'd have to add snippetAreas in the presenter and also invalidate them in presenter on each AJAX call, am I getting this right?

**Comment by hrach** [comment]
@juniwalk yeah, seems correct.

**Comment by juniwalk** [comment]
So I tried the sub-components way and @matej21 was right, it is even superior to partial rendering. Thank you guys for your help.
