### ISSUE TITLE
Set template variables using ArrayAccess

### ISSUE THREAD

**Issue by richard-ejem** [nette/application#165]
I'm thinking why Nette\Bridges\ApplicationLatte\Template is using object access to set template attributes? Wouldn't ArrayAccess be more natural?

When using `$template->foo = 'bar';`, i.e. PhpStorm warns about accessing field via magic method.

I think `$template['foo'] = 'bar';` would:

1. be more expressive - there is actually a hashmap of template variables, they are not "template object properties"
2. not generate warnings about usage of magic in IDEs

What do you others think?

**Comment by TomasVotruba** [comment]
You are right, it now uses magic methods and there are better ways to do that. Array access would be just different kind of magic.

Since we are in PHP code, we can use help of already existing methods and IDE.
There are two:

```php
$template->add('foo', $bar);
```

or

```php
$template->setParameters(
    'foo' => $bar
);

I prefer the last one, calling once in the end. It's more immutable-like and leading to less *value overridden* bugs.


Both methods are by default in [Application\...\Template](https://github.com/nette/application/blob/7b07c4e3aa150fdea0b7765a7223bca621136689/src/Bridges/ApplicationLatte/Template.php#L140-L163
) class.

---

To enabled it easily in your IDE, just add annotation to your `AbstractBaseController`:

```php
/**
 * @property-read Nette\Bridges\ApplicationLatte\Template $template
 */
abstract class AbstractBasePreseter extends Presenter
{
}
```

**Comment by richard-ejem** [comment]
You are true, the setParameters() method is suitable (altrough for scaffolding and debugging, the template->var or my proposed template['var'] is useful).

The ArrayAccess interface is a bit magic, but imho a language feature far less magical than magic properties (clearly declared by using interface, more expressive in the manner that the key could be any string). The add() method is unnecessarily verbose for debug/scaffolding.

So my opinion is still that replacing the magic with notably less magical shortcut would be good (if not to deprecate the magic at all).

**Comment by dg** [comment]
It does not make sense to change it, everyone uses it.
