### ISSUE TITLE
n:nonce isn't replaced if <script> is placed inside HTML comment

### ISSUE THREAD

**Issue by radekdostal** [nette/application#171]
- bug report? yes
- feature request? no
- version: 2.4.4

### Description
Attribute n:nonce isn't replaced if `<script>` is placed inside HTML comment.

### Steps To Reproduce
```
<!--[if lt IE 9]>
  <script n:nonce src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script n:nonce src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
```

**Comment by dg** [comment]
Conditional comments are not supported by Latte (and even not by Microsoft).
