### ISSUE TITLE
Empty flash messages when template is created before Presenter::startup()

### ISSUE THREAD

**Issue by vlastavesely** [nette/application#174]
- bug report? yes

I found an another issue but I am not really sure what solution would be the best.

When it happens that method `Presenter::createTemplate()` is called before `Presenter::initGlobalParameters()`, a template cannot load flash messages from a previous request properly for parameter `_fid` has not been set yet. It can happen when you create function `Presenter::injectSomething()` that touches template by setting some parameter into it. In my case, I was trying to inject a translator and set a param `$lang` to the template in the same function. After redirect I was not able to load presenter's flash messages.

Question is how to solve it. First logical solution might be to force reload the flash messages from session right before template is sent to a browser. 

Another way to go would be just to trigger a warning and consider template creation before `Presenter::run()` has been called as bad practice. This is because I am wondering how good practice it can be to use other dependencies from a `inject*()` and rely on that they were really already set...? Wouldn't be `inject*()` functions ideally only for setting dependencies and nothing more?

Any other suggestions?

**Comment by JanTvrdik** [comment]
You MUST NOT touch template in `Presenter::injectSomething()` because the class is not yet initialized. The same is true for constructor.

**Comment by vlastavesely** [comment]
I agree, I moved it into `beforeRender()`. But it can happen to someone other so user should be warned that he does something he should not doing.
