### ISSUE TITLE
Ambiguous  storing Flash Message in Templates

### ISSUE THREAD

**Issue by TomasVotruba** [nette/application#178]
- bug report? not sure
- feature request? no
- version: 2.4

### Description

When storing flash message in component, it is in session but not in template - because there are 2 possible templates.

Located in [flashMessage()](https://github.com/nette/application/blob/d0f19faf7301197049ccd9fa9eda9419e85d9ea5/src/Application/UI/Control.php#L80-L81) method:

```php
$this->getTemplate()->flashes = $messages;
$this->getPresenter()->getFlashSession()->$id = $messages;
```

and sessions are set to template only in `Presenter` in [TemplateFactory](https://github.com/nette/application/blob/d0f19faf7301197049ccd9fa9eda9419e85d9ea5/src/Bridges/ApplicationLatte/TemplateFactory.php#L121-L124):

```php
if ($presenter instanceof UI\Presenter && $presenter->hasFlashSession()) {
	$id = $control->getParameterId('flash');
	$template->flashes = (array) $presenter->getFlashSession()->$id;
}
```

### How to Simulate

```php
// Control

final class MyControl extends Control
{
    public function process()
    {
        // case A          
        $this->flashMessage('Log in, bro!');
        $this->presenter->redirect('SomePresenter:default');
        // vs.    
        // case B
        $this->presenter->flashMessage('Log in, bro!'); 
        $this->presenter->redirect('SomePresenter:default');
    }
}
```

    

### Case A

- stores in global session
- stores in control template

### Case B

- stores in global session
- stores in presenter template

This is difficult to debug, because it is in Session in both cases.

Not sure how to solve this. Any ideas?

**Comment by misaon** [comment]
Like this $this->presenter->flashMessage('Log in, bro!'); ?
