### ISSUE TITLE
Persistent parameter doesn't work with traits

### ISSUE THREAD

**Issue by martinknor** [nette/application#183]
- bug report? yes
- version: 2.4.6

### Description
When i have persistent parameter in trait, routes with this parameter don't work. Probably problem is here: `\Nette\Application\UI\Presenter::argsToParams` because reflection cannot load parameters from trait.

### Steps To Reproduce
```php
trait PresenterTrait
{
	/** @persistent */
	public $locale;
}

class DefaultPresenter extends  \Nette\Application\UI\Presenter
{
	use PresenterTrait;
}

class SecondPresenter extends  \Nette\Application\UI\Presenter
{
	use PresenterTrait;
}

**Comment by dg** [comment]
It is not bug report, it is feature request, because persistent parameters works the same way as in this case

```php
class DefaultPresenter extends  \Nette\Application\UI\Presenter
{
	/** @persistent */
	public $locale;
}

class SecondPresenter extends  \Nette\Application\UI\Presenter
{
	/** @persistent */
	public $locale;
}
