### ISSUE TITLE
param2path failed when given integer

### ISSUE THREAD

**Issue by MartkCz** [nette/application#185]
- bug report? yes
- feature request? no
- version: dev-master f0b30ff

### Description
I tried to generate link:
```html
{plink News:detail category => $news->getCategory()->getName(), id => $news->getId(), name => $news->getSubject()}
```

and it's failed in class Route in method param2path: https://github.com/nette/application/blob/master/src/Application/Routers/Route.php#L330

TypeError: Argument 1 passed to Nette\Application\Routers\Route::param2path() must be of the type string, integer given

Dump of params:
category => "xxx"
id => 3614
name => "xxx"
action => "xxx"

It's ok:
```html
{plink News:detail category => $news->getCategory()->getName(), id => (string) $news->getId(), name => $news->getSubject()}
```

**Comment by dg** [comment]
It should be converted to string here https://github.com/nette/application/blob/f0b30ff524927fc9a9d785efee1d3666576aba70/src/Application/Routers/Route.php#L311.  Can you find out why this is not happening?

**Comment by MartkCz** [comment]
Because fixity is not set. Values of $meta:
```php
pattern => "#(?:[0-9]+)\z#A" (15)
filterOut => array (2)
0 => "Nette\Application\Routers\Route" (31)
1 => "param2path" (10)
filterTable2 => null
```
It can cause similiar code like: https://doc.nette.org/cs/2.1/routing#toc-masky

**Comment by MartkCz** [comment]
I tried test case Routers/Router.basic.phpt with int parameter:
ok:
```php
Assert::same('http://example.com/homepage/12', testRouteOut(new Route('<presenter>/<id= \d{1,3}>'), 'Homepage', ['id' => 12]));
```

failed:
```php
Assert::same('http://example.com/homepage/12', testRouteOut(new Route('<presenter>/<id [0-9]+>'), 'Homepage', ['id' => 12]));
```
