### ISSUE TITLE
Calling method `checkRequirements` for Controls

### ISSUE THREAD

**Issue by zeleznypa** [nette/application#188]
- bug report? no
- feature request? yes
- version: 2.3.x

### Description
There is a method `checkRequirements()` in file [PresenterComponent.php](http://ptest.troja.mff.cuni.cz/nette/API-reference/source-Application.UI.PresenterComponent.php.html#113) which is great for Auth operations and also for some Status checks. It will be usefull IMHO, to call this method also for [Nette\Application\UI\Control](https://github.com/nette/application/blob/v2.3/src/Application/UI/Control.php#L18) which extends the `PresenterComponent` class. For example in process of [registering component in ContainerTree](https://github.com/nette/component-model/blob/master/src/ComponentModel/Container.php#L70)

**Comment by JanTvrdik** [comment]
You can easily implement this yourself by simple overriding method `validateChildComponent()`.
