### ISSUE TITLE
Route: static text not matched

### ISSUE THREAD

**Issue by repli2dev** [nette/application#207]
Version: 2.4.13 (tested also 2.4.4)

### Bug Description

In one project we have a following routes:
```
$router[] = new Route('//[!www.]<domain>/<lang>/news/<action>[/<id>]', [
            'presenter' => 'News',
            'action' => 'default',
            'lang' => null,
        ], IRouter::ONE_WAY);
$router[] = new Route('//[!www.]<domain>/<lang>/<presenter>/<action>[/<id>]', [
            'presenter' => 'Homepage',
            'action' => 'default',
            'lang' => null
        ]);
```

And from my understanding I expect the last to be matched for the `GET /` request. However the first is matched.

### Steps To Reproduce

1. Use the routes
2. `GET /` will get user to Homepage:default

### Expected Behavior

The News:default is displayed.

### Investigation

I went to the `Route::match` and the regular expression for the first (and wrongly matched) route is
`#//(?:www\.)?(?P<p10>(?U)[^/]+)/(?:(?P<p14>(?U)[^/]+)/news/(?:(?P<p18>(?U)[a-z][a-z0-9-]*)(?:/(?P<p27>(?U)[^/]+))?)?)?/?\z#A`

And the address `//www.foo.test/` matches as there is one `?` which makes whole Query String non-mandatory. Is this a bug?

**Comment by milo** [comment]
I tried few combination and I'm not sure, why following match.
```
composer require nette/application
```
```php
<?php
# test.php

require __DIR__ . '/vendor/autoload.php';

use Nette\Application\IRouter;
use Nette\Application\Routers\Route;
use Nette\Application\Routers\RouteList;

$router = new RouteList;

$router[] = new Route('<lang>/test', [
    'presenter' => 'Test',
    'action' => 'default',
    'lang' => null,
]);

$url = $_SERVER['argv'][1] ?? 'https://example.com/';
$httpRequest = new Nette\Http\Request(
    new Nette\Http\UrlScript($url)
);

$appRequest = $router->match($httpRequest);
echo "URL: $url\n\n";
if ($appRequest === null) {
    echo "Not match!\n";
} else {
    echo "Match: {$appRequest->getPresenterName()}\n";
    print_r($appRequest->getParameters());
}
```

```
URL: https://example.com/

Match: Test
Array
(
    [action] => default
    [lang] =>
)
```

**Comment by dg** [comment]
It is caused by `'lang' => null` in first route, remove it.

**Comment by repli2dev** [comment]
@dg Thanks for explonation, with removing this code it starts to work in the case that `lang` is mandatory... In our case this was unwanted (due to back compatibility we needed to match `/news` and `/<lang>/news` and both to redirect to new URL... We bypassed the issue with using route filter tables.

**Comment by milo** [comment]
@repli2dev Or, you can add on more route `'//[!www.]<domain>/news/<action>[/<id>]'`

**Comment by dg** [comment]
> we needed to match /news and /<lang>/news

`Route('//[!www.]<domain>/[<lang>/]news/<action>[/<id>]'`
