### ISSUE TITLE
Missing / deleted variable

### ISSUE THREAD

**Issue by Lumeriol** [nette/application#209]
Version: 3.0.dev
From commit: f66afb9b5bf1a48ad73fe732cbcc2c7974132d25

### Bug Description
Undefined variable: tmp in ...\Application\Routers\RouteList.php on line 64
(function constructUrl())

### Steps To Reproduce
Nette with defined modules in Router

### Possible Solution
Replace deleted $tmp variable by $params[self::PRESENTER_KEY]

**Comment by dg** [comment]
Thanks, fixed
