### ISSUE TITLE
nette/application 2.4 is not compatible with nette/utils 3.0

### ISSUE THREAD

**Issue by xificurk** [nette/application#210]
Version: 2.4.x

### Bug Description
composer.json allows `nette/utils ~3.0.0`, but it's not compatible because of at leaset one missing return type:
`Fatal error: Declaration of Nette\Application\Routers\RouteList::offsetSet($index, $route) must be compatible with Nette\Utils\ArrayList::offsetSet($index, $value): void`

### Possible Solution
Probably the only way out of this is to remove `nette/utils 3.0` from allowed dependencies.

**Comment by dg** [comment]
Fixed
