### ISSUE TITLE
Make Presenter::restoreRequest() parameter nullable

### ISSUE THREAD

**Issue by milo** [nette/application#215]
Is there some issue with making `Presenter::restoreRequest()` parameter `?string` type? 

https://github.com/nette/application/blob/b0a56e3836616f244e91095495d5c9fc9b8487c2/src/Application/UI/Presenter.php#L1045

I used to use it in this way:
```php
/** @persistent */
public $backLink;
```

Fix to default `''` is easy, I just want to be sure this is intentional.

**Comment by dg** [comment]
I think `string` is more correct, `?string` is more comfortable.

**Comment by milo** [comment]
Correct is better :)
