### ISSUE TITLE
redirect() typehints at v3.0.0.

### ISSUE THREAD

**Issue by BigOHenry** [nette/application#220]
Version: 3.0.0

### Bug Description
Getting phpstan lvl5 error on `$this->redirect('Home:', ['name' => 'test']);` - `Parameter #2 $destination of method Nette\Application\UI\Component::redirect() expects string|null, array<string, string> given.`

### Steps To Reproduce
```
$this->redirect('Home:'); // this is OK 
$this->redirect('Home:', ['name' => 'test']); // there is the phpstan error 
$this->redirect(200, 'Home:', ['name' => 'test']); // first parameter $code is deprecated; use redirectPermanent() for 301 redirect.
```

### Expected Behavior
- there should not be phpstan errors

### Possible Solution
1) Fix type hints for $destination parameter to `string|array|null`.
or 
2) Remove `$code` parameter from method completely. Dont know if there is any usage of it.

**Comment by dg** [comment]
> Remove $code parameter from method completely.

Seems like good solution. Can you send PR?

**Comment by mabar** [comment]
Related to #212 and #221 (alternative solutions)

**Comment by BigOHenry** [comment]
> Remove $code parameter from method completely.
> 
> Seems like good solution. Can you send PR?

PR ready. Its ok like this?
