### ISSUE TITLE
Container is sometimes being rebuilt on every request even though nothing changed

### ISSUE THREAD

**Issue by finwe** [nette/application#227]
Version: 
- application: v3.0.1
- bootstrap: v3.0.0
- di: v3.0.1

### Bug Description

According to Tracy Bar, the application sometimes falls to a state when the container is being rebuilt on every request.

This is a result of the condition `$files !== $currentFiles` in `DependencyChecker::isExpired` call being true. All compared files are equal except for `temp/cache/nette.application/touch` timestamp of which differs for about 2 seconds.

### Steps To Reproduce

n/a. Unfortunately, this comes and goes and I haven't yet discovered the exact cause.

### Expected Behavior

The container is being rebuit only when something actually changed.

### Possible Solution

Compilation of the container takes about 500-1500 ms based on Tracy panel. Maybe the timestamps are saved on opposite sides of the compilation and therefore the difference?

**Comment by dg** [comment]
These concurrent things are really mindblowing.

Just thinking… Could the cache play a role in this? Can you try call `clearstatcache()` before this line https://github.com/nette/di/blob/master/src/DI/DependencyChecker.php#L74 and/or before this line https://github.com/nette/di/blob/master/src/DI/DependencyChecker.php#L86?

**Comment by finwe** [comment]
Not really, I'm afraid.

After dev machine reboot and disabling xdebug, the container rebuild time is about 50ms and it is being rebuilt on about every second reload.

**Comment by mabar** [comment]
I am not sure if it's a best solution but these problems are related to https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/PresenterFactoryCallback.php#L47 and https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/ApplicationExtension.php#L152 PresenterFactoryCallback could not find presenter registered as a service and it triggers container rebuild, so you may have automatic registration of presenters misconfigured.
Most safe solution I found is replacement of callback with one which strictly requires presenter to be registered https://github.com/modette/modette/blob/master/packages/core-ext-ui/src/DI/PresenterFactoryCallback.php

**Comment by finwe** [comment]
@mabar You are probably right, yet I don't use any custom presenters registration - yes, presenters with scalar dependencies are registered manually in services config, but nothing custom apart from that.

**Comment by dg** [comment]
Btw in the next bigger release I would like to move on to something like modette PresenterFactoryCallback and get rid of the dynamic creation of presenters.

**Comment by mabar** [comment]
Manual registration is totally ok, I have it as a enforced requirement. Problematic is autodiscovery - you may just forgot to add folder with your presenters to scanDirs. Or if you have scanComposer enabled then be aware of fact it can find only classes from classmap - PSR-4 namespaces are not searched

**Comment by mabar** [comment]
@dg ❤️ Glad to hear it

**Comment by finwe** [comment]
Presenters are loaded with robotLoader. Is simple robotloader configuration not enough? No scanDirs directive set, but looking to the source, scanDirs just sets the robotloader the same way.

**Comment by dg** [comment]
> Is simple robotloader configuration not enough?

No, because compiler has not access to RobotLoader, it must be configured via scanDirs.

**Comment by finwe** [comment]
Is that documented? When I remove `$this->configurator->createRobotLoader()` from my Bootstrap and add scanDirs to application in config.neon, presenter classes are not found.

    Nette\DI\ServiceCreationException: Service '028': 
    Class AdminModule\UploadPresenter not found

**Comment by finwe** [comment]
Oh, keeping both bootstrap robotLoader _and_ scanDirs fixes this.

Couldn't this be easier? Will incorporating _something like modette PresenterFactoryCallback_ solve this?

**Comment by dg** [comment]
I tried to modify it to use an external robotloader.
