### ISSUE TITLE
Feature request: new method Link::isLinkCurrent()

### ISSUE THREAD

**Issue by MartkCz** [nette/application#229]
I want check lazy link if is current, but I can't because of private $component

```php
class TabsComponent {

    public function addLink(string $name, Link $link)

}
```

Solution is:

```php
class Link {

    public function getComponent(): Component

}
```

or better

```php
class Link {

    public function isLinkCurrent(): bool {
        return $this->component->isLinkCurrent($this->destination, $this->parameters);
    }

}
```

I'm willing to write a PR

**Comment by mabar** [comment]
`$tabsComponent->isLinkCurrent($link->getDestination(), $link->getParameters())` would not work?

**Comment by MartkCz** [comment]
It doesn't work, when link is from presenter I must call `$this->getPresenter()` when from other component, I have to call `$this['component']->isLinkCurrent()`, but I don't know from which component link is created, because of private property $component
