### ISSUE TITLE
Typed persistent parameters

### ISSUE THREAD

**Issue by jtojnar** [nette/application#230]
Currently, the components’ persistent parameters are only converted to a type when they have default value:

https://github.com/nette/application/blob/9483f4320f7dcf2de2cca656125ac1b10f23f7fb/src/Application/UI/Component.php#L138-L139

Sometimes, the value can only be set dynamically but we would still like for it to be properly converted in `loadState`.

I propose recognizing typed annotations like `@var int @persistent`

It would need to be extracted [here](https://github.com/nette/application/blob/9483f4320f7dcf2de2cca656125ac1b10f23f7fb/src/Application/UI/ComponentReflection.php#L54) and then handled in the function above.

I can implement this if you agree.

**Comment by dg** [comment]
Can you better describe what situation you want to deal with?

**Comment by jtojnar** [comment]
The [`VisualPaginator`](https://github.com/aleswita/VisualPaginator) component has two persistent properties: `$page` and `$itemsPerPage`. In `loadState` method, they are assigned to the corresponding properties of [`Nette\Utils\Paginator`](https://api.nette.org/3.0/Nette/Utils/Paginator.html). With `strict_types` on this fails unless we manually convert the properties to `int`, which, while being a [trivial modification](https://github.com/aleswita/VisualPaginator/pull/3/commits/c9fcd15ceb884c3c6278ba55dc3c704417b89b59), feels like something that our framework could spare us doing.

And indeed, it does convert the type for us when we set a default value. However, that is not always possible. We can assign the default value `1` for the `$page` property statically but the default value of `$itemsPerPage` depends on another property `$itemsPerPageList`, which can be modified after the construction of `VisualPaginator`. In that case it is not right to set default value to some dummy number because then, the component could be internally inconsistent (`$itemsPerPageList[$itemsPerPage]` needs to exist).

Setting the type to `?int`, Nette could easily convert the value of the persistent property in the background like it does with properties that have a default value set, allowing us to clean up the code slightly.

When the parameters are missing, we could use the default value

**Comment by dg** [comment]
I understand, you just need nullable typed property.

I will add them, but I wouldn't probably support the `@var` annotations, but I would add support for type properties in PHP 7.4
