### ISSUE TITLE
Presenter::getTemplate() optional parameter class

### ISSUE THREAD

**Issue by MartkCz** [nette/application#249]
I've following Template structure

```php
abstract class FrontLayout extends StrictTemplate {

    // layout properties

}

final class DetailArticleTemplate extends FrontLayout {

    // template properties

}
```

In FrontPresenter I want validate template if is instance of FrontLayout

```php
function beforeRender() {
    $template = $this->getTemplate(FrontLayout::class); // Throws an error if template is not FrontLayout type 
}
```

Argument is optional, no BC break.

advantages: more strict, phpstorm automatically suggests completion for variable $template without annotation

**Comment by dg** [comment]
I think that `$this->getTemplate(FrontLayout::class);` is confusing, it seems like getter, not validator.

What about `assert($template instanceof FrontLayout)` ?

**Comment by MartkCz** [comment]
you've right
