### ISSUE TITLE
Parent presenter usage ends with "Multiple services of type ... found"

### ISSUE THREAD

**Issue by KacerCZ** [nette/application#258]
Version: 3.0.4

### Bug Description
When presenter class is inherited to another presenter, then parent presenter usage ends with error "Multiple services of type ... found"

### Steps To Reproduce
Create presenter with name `ParentPresenter` and another presenter `ChildPresenter` inheriting from `ParentPresenter`.
Add presenters to composer classmap and dump optimized class loader.
Try access `ParentPresenter` and `BadRequestException` is thrown with message "Multiple services of type ..."

### Expected Behavior
I expect `ParentPresenter` to be run as was in version 2.4.

**Comment by mabar** [comment]
If you request a service and multiple services with same type are found, then error is correct. Parent presenter should either be abstract or you can set `autowired` option so service is wired only by specific name

**Comment by KacerCZ** [comment]
Method `ApplicationExtension::beforeCompile()` already disables autowiring of all presenters.
Class `PresenterFactoryCallback` then uses `findByType()` and multiple services are returned for `ParentPresenter`.

**Comment by dg** [comment]
It is due to cb354357a9f7149d0ee513798dbdab82b14b

**Comment by KacerCZ** [comment]
I've updated to nette/application 3.0.5 and its working as expected.
Thank you.
