### ISSUE TITLE
Routing Panel in Debug Bar: Call to undefined method RouteList::getModule()

### ISSUE THREAD

**Issue by Thommas2316** [nette/application#264]
Version: 3.0.5

### **Bug Description**
Hi,

after updating to 3.0.5, the DebugBar shows an error about _RouteList_ not having method _getModule()_. 
After some investigation the problem seems to be with the transition from _Application\Routers* classes to Nette\Routing*_ (mentioned in release notes for 3.0.5), as the RouteList in nette/application **has** the method, but the one in nette/routing **does not**. 

This line seems to be the culprit:

https://github.com/nette/application/blob/139ae54073c68bba734f85950160ab7788ef5f4e/src/Bridges/ApplicationTracy/RoutingPanel.php#L108

The `$router` in this section is instance of `\Nette\Routing\RouteList` instead of `\Nette\Application\Routers\RouteList` (which has the mentioned method available).

Here is the screen from DebugBar :
![image](https://user-images.githubusercontent.com/3959662/87228725-5b798e80-c3a3-11ea-90cd-a383068753a0.png)

When downgraded to 3.0.4 everything works as expected.

### **Steps To Reproduce**

Upgrade to `nette/application:3.0.5`

### **Expected Behavior**
Working routing panel

### **Possible Solution**
Porting module functionality to RouteList in nette/routing ?

P.S.: Sorry for not sending the pull request with the fix, as I know the line which is buggy, but I don't know the concept behind the transition so I'm not able to fix it (at the moment) :/

**Comment by dg** [comment]
Should be fixed, can you check it?

**Comment by Thommas2316** [comment]
Problem solved.

Thank you for such a quick fix and have a nice rest of the day :)
