### ISSUE TITLE
User defined exception should be rewrited as 404 error

### ISSUE THREAD

**Issue by janbarasek** [nette/application#266]
Hello,

Very often I call a database query directly in the Presenter, which throws a certain type of exception in case of failure (or if it does not return any result). This behavior can be well demonstrated, for example, at Doctrine:

```php
public function actionDetail(string $id): void
{
   $this->template->article = $this->em->getRepository(Article::class)
      ->createQueryBuilder('article')
      ->where('article.id = :id')
      ->setParameter('id', $id)
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult();
}
```

The `getSingleResult()` method throws a`NoResultException` if no result is found.

I think there could be an optional section in the configuration Neon where you can list user-defined exceptions (data types) that will be automatically converted to a `BadRequestException`. This is another level of system protection, and the developer does not have to handle the output of all queries manually.

Thanks.

**Comment by dg** [comment]
The error presenter is used for this, where you decide how to handle the error.
