### ISSUE TITLE
Design flaw: Obscure events

### ISSUE THREAD

**Issue by dakujem** [nette/application#268]
Version: ALL versions of Nette, multiple packages

### The Problems

The whole problem is caused by **unnecessary magic**.

```php
use Nette\SmartObject;

class Father
{
    use SmartObject;

    public $onSuccess = [];

    public function doStuff()
    {
        $this->onSuccess($this); // What does this do exactly? 🤔
    }
}
```

First, **any event can easily be shadowed by implementing a method of the same name**.

Furthermore, **IDEs do not cope with this kind of magic** (tried Netbeans and PHPStorm).

Finally, from a human developer perspective, it is not clear at the first sight, what happens with the call.

You will object that this is something that any Nette developer should know, but why introduce this magic when it's not needed? Well, I've seen this done. There are novices, too. And there are people that do not work with Nette regularly.

![image](https://user-images.githubusercontent.com/443067/99559615-45b94d00-29c5-11eb-9398-f73296f13234.png)

### Steps To Reproduce

```php
use Nette\SmartObject;

class Father
{
    use SmartObject;

    public $onSuccess = [];

    public function doStuff()
    {
        $this->onSuccess($this);
    }
}

class Son extends Father
{
    public function onSuccess()
    {
        throw new LogicException('This is an error.');
    }
}

$father = new Father();
$father->onSuccess[] = function () {
    echo "OKAY, Works as expected.\n\n";
};

$son = new Son();
$son->onSuccess[] = function () {
    echo 'Sorry, this will never be seen.';
};

// this will print "OKAY, Works as expected."
$father->doStuff();

// this will throw "PHP Fatal error:  Uncaught LogicException: This is an error."
$son->doStuff();
```

### Proposed Solution

I propose that the events are not handled automagically, but by an explicit call.

It is more verbose, but there are clear benefits:
1. it is immediately clear to _any_ reader that it is an event being handled (even without the knowledge of Nette)
2. IDEs will understand the call
3. static analyzers will understand the call
4. the call can not be shadowed by implementing method with the same name as the event
5. there is no need to use `ObjectHelpers::hasProperty` which uses `Reflection`, a slight performance bonus

```php
final class NetteEventHandler
{
    public static function fire(?iterable $handlers, ...$args)
    {
        foreach ($handlers ?? [] as $handler) {
            $handler(...$args);
        }
    }
}

class Father
{
    use SmartObject; // may still be used for other benefits

    public $onSuccess = [];

    public function doStuff()
    {
        NetteEventHandler::fire($this->onSuccess, $this);
    }
}
```
> The above static method call causes tight coupling.
> It could be moved to a trait as a non-static method as well.

![image](https://user-images.githubusercontent.com/443067/99559648-4fdb4b80-29c5-11eb-9130-0f08503fefa5.png)
Better.

The only disadvantage I can think of are cases when the shadowind method is implemented _on purpose_, and the parent's events are either handled manually or not handled by choice, like the following:
```php
class Daughter extends Father
{
    public function onSuccess()
    {
        foreach($this->onSuccess() as $handler){
            $handler($this, 42);
        }
    }
}
```
But I would call this an abusement of the Nette event system, breaking the Liskov principle too.

### Conclusion

I believe this would make Nette a tiny bit more transparent.

I also think it can be implemented without a BC, or at least with minimal impact on dev experience.

Finally, I would like to see the documentation altered as soon as possible,
so that newcomers know about alternatives and avoid using this antipattern.

> As a result, this would also allow a proper return type for `ObjectHelpers::hasProperty` method, which now returns `bool`, as expected ... _except_ when it returns `'event'` string 🤷‍♂️.

### Affected Nette Packages

The issue is most prominent in `nette/application`, since every descendant of `Nette\ComponentModel\Component` inherits it, hence I'm reporting it here, but the flaw is also present in `nette/forms`, `nette/di`, `nette/bootstrap`, `nette/security`, and in any userland object that relies on `Nette\SmartObject` trait to handle the events.

**Comment by dg** [comment]
It can be replaced with `Nette\Utils\Callback::invokeAll` after nette/utils 3.2.1 will be released

**Comment by dakujem** [comment]
Sure, `Nette\Utils\Callback::invokeAll` does exactly what the name implies. However, will the code in the aforementioned Nette packages be rewritten to use it?

There are 2 points in this issue:
1. **Nette code** should stop using magical events for better transparency
2. **Nette documentation** should explain how events are implemented in Nette (avoiding SmartObject of course)

Currently, the docs largely neglect explaining events, the only 3 references to events I could find are these 3: [SmartObject](https://doc.nette.org/en/3.1/smartobject#toc-events), [Presenters](https://doc.nette.org/en/3.1/presenters#toc-events) and [Forms](https://doc.nette.org/en/3.1/form-presenter).

In my opinion, events in Nette are very elegant and simple, there is no need for the added magic, though.

**Comment by dg** [comment]
Replaced with `Arrays::invoke()`.

**Comment by dakujem** [comment]
Need help with the docs?

**Comment by dg** [comment]
Yeah, sure.

**Comment by dakujem** [comment]
@dg David, I was thinking about `Arrays::invoke`.... While they do exactly what I suggested in this topic, I really suggest implementing something more descriptive here, like `Events::handle` or `EventHandler::fire`. Why? For better code legibility.

Internally, it can of course use the generic `Arrays::invoke`.
```
final class Events
{
    public static function handle(?iterable $handlers, ...$args): array
    {
        return Arrays::invoke($handlers, ...$args);
    }
}
```

It's a subtle change, but it makes the code more obvious.

**Comment by dg** [comment]
That would be an unnecessary "fogging". I think it's better when it's clear that it's a normal array of callbacks and that they are normally invoked, without magic.

**Comment by dakujem** [comment]
Okay, I get your point of view. Once devs get the grasp of what `Arrays::invoke` does, the meaning of the code will be clear. To me, `Events::handle` is even more obvious, but it's also much better as it is now, than it was before.
