### ISSUE TITLE
Missing layout when used with latte 2.9.0

### ISSUE THREAD

**Issue by jkavalik** [nette/application#269]
We set layout to our templates via the `findLayoutTemplateFile()` and not the `{layout}` macro.
After update to latte 2.9.0 the layout is gone. I debugged it a bit and found a problem possible in `UIMacros.php` (or in template generation?)

```
public function finalize()
	{
		return [$this->extends . 'Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->parentName, $this->blocks);'];
	}
```
references `$this->blocks` which is empty in the newly generated template php files, the data being put into `static::BLOCKS` instead. If I rewrite that line to use that, it starts to work again.

latte 2.8.3:
```
final class Template9bc4837973 extends Latte\Runtime\Template
{
	public $blocks = [
		'content' => 'blockContent',
	];

	public $blockTypes = [
		'content' => 'html',
	];
...
```
latte 2.9.0:
```
final class Templatee7982bf00d extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['content' => 'blockContent'],
	];

	public $blocks = [];

	public $blockTypes = [];
...```

**Comment by dg** [comment]
The `public $blocks = [];` should definitely not be in the template class. Are you using any other extensions for Latte?

**Comment by jkavalik** [comment]
Kdyby/TranslationExtension touches Latte, but afaik nothing about blocks in there, similarly Contributte\FormMultiplier, there are other extensions (Honeypot, Redis, NextraxORM, Monolog.. but these should not touch latte at all.

**Comment by jkavalik** [comment]
Contributte\FormWizard adds some new Latte macros but again nothing about blocks

**Comment by jkavalik** [comment]
Thanks to your pointer I found a project-specific MacroSet that is adding it for some reason.
Closing this. Thank you for your time.
