### ISSUE TITLE
get_class() expects parameter 1 to be object, null given when askingto non existing component.

### ISSUE THREAD

**Issue by tprochazka** [nette/application#280]
Version: 3.1.1

I'm not sure it is bug inside of "uestla/twigrid": "12.0.0", but it is caused by this 
https://github.com/nette/application/commit/d07e7fb3b9bd1ca96ff812d06fff89a7067e2c69#diff-7a8f912d3df1a220bc6b3bd2a76c2b70515bbe575ede15f6c665b4f9569740f8

If parent call return null (component doesn't exists) this new code crash on `get_class() expects parameter 1 to be object, null given`. Is it correct behavior<

twigrid doe this:

    if (!isset($this['columns'])) {
        $this['columns'] = new NContainer;
    }
 
Which causes us to attempt to instantiate the component which doesn't exist.
I think that it is a bug also in twigrid.
But the question is if it really should crash in this way when a component doesn't exist.

Here is how looksfull stack
![image](https://user-images.githubusercontent.com/172094/107129626-fb11e780-68c6-11eb-8426-51cbc9e7c068.png)

**Comment by dg** [comment]
It is fixed is master
