### ISSUE TITLE
Do not log "Parameter callback is not a valid closure"

### ISSUE THREAD

**Issue by janbarasek** [nette/application#281]
Almost every week, I receive dozens of emails from Tracy that various users are trying to call a potentially dangerous URL from CVE.

I think it's almost always an error that we don't need to log, because we just need to call a few different URLs on the web and it immediately fills the folder with logs on the server, even though it should be rewritten to a 404 error.

Exception message: `Nette\InvalidStateException: Parameter callback is not a valid closure.`.

I suggest rewriting errors of this type to a 404 level error and not logging anything.

Thanks.

**Comment by dg** [comment]
I see in the code `throw new Application\BadRequestException('Parameter callback is not a valid closure.');`

**Comment by JanTvrdik** [comment]
https://github.com/nette/application/commit/85994596b09a26b2c2be09f4234787fa69d71376
