### ISSUE TITLE
Presenter::createTemplate() cannot be used twice in presenter life cycle

### ISSUE THREAD

**Issue by lulco** [nette/application#282]
Version: 3.1.2

### Bug Description
I am trying to use `createTemplate()` in `actionDefault()` and `renderDefault()` because I need to add some variables in both methods. Problem is that `renderDefault()` creates the whole new Template, so variable `foo` from `actionDefault()` is undefinded. It works if `$template = $this->createTemplate(ATemplate::class);` is replaced with `$template = $this->template;` but there is magically created template name, which is not possible to use if Template is in different namespace like Presenter.

### Steps To Reproduce
```
<?php

use Nette\Application\UI\Presenter;
use Nette\Bridges\ApplicationLatte\Template;

class APresenter extends Presenter
{
    public function actionDefault()
    {
        $template = $this->createTemplate(ATemplate::class);
        $template->foo = 'bar';
    }

    public function renderDefault()
    {
        $template = $this->createTemplate(ApiTemplate::class);
        $template->bar = 'baz';
    }
}

class ATemplate extends Template
{

}
```

### Expected Behavior
There will be only one template in Presenter / Control life cycle and it will keep all variables from both methods (action, render).

### Possible Solution
I am not sure if it is a good solution, but maybe we can save result of `createTemplate()` to `$this->template` like it is in `getTemplate()`.

**Comment by dg** [comment]
In Nette, all methods named `createXyz` create a new object without side effects. This behavior is correct.

You can save the `$template` variable in your custom variable.

**Comment by lulco** [comment]
OK, I understand, thanks.
