### ISSUE TITLE
Error: Typed property $templateFactory is accessed before initialization

### ISSUE THREAD

**Issue by Lumeriol** [nette/application#289]
Version: 4.0-dev

### Bug Description
An error "Typed property Nette\Application\UI\Control::$templateFactory must not be accessed before initialization" occured when try to access Template property in component, respectively problem is with extending Control (not in presenters).

### Steps To Reproduce
This problem starts with PHP 8.0.x and Nette/Application 4.0-dev (sandbox). On v3.1 (with PHP 8.x) looks like all correct.

```
class Xy extends Control
{
	public function render(): void
	{
		$this->template->var = 123;
		$this->template->setFile(__DIR__ . '/' . self::getReflection()->getShortName() . '.latte');
		$this->template->render();
	}
}
```

### Possible Solution
There should be `private ?TemplateFactory $templateFactory = null;` instead `private TemplateFactory $templateFactory;` in Application\UI\Control.php

**Comment by dg** [comment]
fixed
