### ISSUE TITLE
Routing panel throws exception from UrlScript

### ISSUE THREAD

**Issue by MartkCz** [nette/application#299]
Version: 3.1.5

![image](https://user-images.githubusercontent.com/10145362/150678519-e59aa294-9e42-4014-8dba-212e147df4cf.png)
![image](https://user-images.githubusercontent.com/10145362/150678545-c125da32-b844-46ab-98ac-e95a65c5cde4.png)

etc.

```php
$router->withModule('Api')->withPath('api')->addRoute(...);
```

**Comment by dg** [comment]
I hope it was fixed by 63f824c1e1e3462d45d95b61394905dd8ea8b3ba
