### ISSUE TITLE
Nette Application 3.1.12 breaks compatibility with Latte 2

### ISSUE THREAD

**Issue by xificurk** [nette/application#315]
Version: 3.1.12

### Bug Description
New options added to LatteExtension in b01ebf7d8b47d5691343be3a912a948c11a52902 broke compatibility with Latte 2. `setStrictParsing()` and `enablePhpLinter()` is not supported in any 2.x version of Latte.

### Steps To Reproduce
Try to create and run new project from https://github.com/nette-examples/quickstart on PHP 7.4
DI compilation fails on `LogicException: Call to undefined method Latte\Engine::setStrictParsing().`

### Expected Behavior
running app

### Possible Solution
Apply the config conditionally only for Latte 3, or drop Latte 2 support.

**Comment by dg** [comment]
fixed
