### ISSUE TITLE
Custom form macros are overridden by default ones

### ISSUE THREAD

**Issue by hrach** [nette/application#320]
Version: 3.1.14

### Bug Description

Adding an extension that defines Latte tags like `input` has no effect, as the default template factory re-registers the default form macros that override the custom ones.

https://github.com/nette/application/blob/e3d05b36c6bcdaf967911d964eb7d04a95f2d5d4/src/Bridges/ApplicationLatte/TemplateFactory.php#L60-L62

### Expected Behavior
A custom-defined extension takes precedence.

Alternatively, couldn't be this configurable?

**Comment by dg** [comment]
Maybe `order()` could solve this: https://latte.nette.org/en/creating-extension#toc-gettags
