### ISSUE TITLE
Tracy red exception page not displayed on BadRequestException

### ISSUE THREAD

**Issue by mildabre** [nette/application#324]
Version: ?.?.?

### Bug Description

After upgrade nette/application from 3.2.0 to 3.2.1, tracy no upgrade (2.10.5),Tracy displays not red exception page on BadRequestException, on other exception works Tracy OK. Tracy displays instead error4xx page.

The bug appears when:

no catchException is in configuration + BadRequestException is thrown

When set in configuration catchException = false, Tracy works OK

In previous versions nette/application until 3.2.0 Tracy works OK also with no catchException configuration

**Comment by stpnkcrk** [comment]
That’s expected behaviour as per https://forum.nette.org/cs/36363-nette-application-3-2-oddeleni-4xx-a-5xx-error-presenteru-na-urovni-konfigurace (last sentence).

**Comment by mildabre** [comment]
@stpnkcrk 

yes, it's not a bug, but a function change in the new version of nette/application described in the documentation: https://doc.nette.org/cs/application/configuration#toc-application, so I'm closing the issue
