### ISSUE TITLE
PresenterFactoryCallback fails to create Presenter

### ISSUE THREAD

**Issue by KminekMatej** [nette/application#330]
Version: 3.2.4

### Bug Description
Refactoring of `PresenterFactoryCallback::__invoke` #ce26e0d fails to resolve classname of Presenter, when resolving inherited presenter.

### Steps To Reproduce
Structure:
```
class RootPresenter extends Presenter{}
class FormPresenter extends RootPresenter{}
```

`$services = ["application.108", "application.112"];`

### PresenterFactoryCallback::__invoke
Previously:
```
$exact = array_keys(array_map($this->container->getServiceType(...), $services), $class, strict: true); // [0 => 1]
if (count($exact) === 1) {
    return $this->container->createService($services[$exact[0]]); //createService("application.112")
}
```

Current:
```
if (count($services) > 1) {
	$services = array_keys(array_map($this->container->getServiceType(...), $services), $class, strict: true); // [0 => 1]
}
if (count($services) === 1) {
        return $this->container->createService($services[0]); //createService(1)
}
```

### Expected Behavior
Pass proper name to createService() function

### Possible Solution
Avoid accidentally rewriting `$services` variable - probably keeping `$exact`

**Comment by dg** [comment]
fixed
