### ISSUE TITLE
case sensitivity in templates' path

### ISSUE THREAD

**Issue by bazo** [nette/application#54]
why is nette suddenly case sensitive?
if I had templates stored in this manner templates/**Homepage**/default.latte and router and links defined with small first  letter like this
````
    new Route('<presenter>/<action>[/<id>]', 'homepage:default');
````
it worked both on windows and linux

after I updated nette, it is looking for templates/**homepage**/default.latte which throws 404s on linux server

**Comment by JanTvrdik** [comment]
> why is nette suddenly case sensitive?

Because it makes Nette both faster and simpler. Fix your application.

**Comment by dg** [comment]
Nearly whole PHP is case sensitive, file system is case sensitive, so it is better to be case sensitive in these areas too.

For questions use forum please.

**Comment by bazo** [comment]
actually, this was not a question.

as long as i don't have to ucfirst all links in the app then it's no big deal, but i don't consider case sensitivity in this case as and advantage. 

lowercased presenter reference in the code look much better than case sensitive. and it prevents accidental errors
