### ISSUE TITLE
Broken co-operation with Kdyby/Console

### ISSUE THREAD

**Issue by solcik** [nette/application#58]
Hello,

this commit (f06a689) / pull (#56) broke co-operation with [Kdyby/Console] (https://github.com/kdyby/console), because of autoloading classes with "Presenter" in their class name from Composer.

In Kdyby [DI extension](https://github.com/Kdyby/Console/blob/master/src/Kdyby/Console/DI/ConsoleExtension.php#L42)
is Kdyby\Console\Application not registred, if request is not from cli mode.

And therefore error come:
"Service of type Kdyby\Console\Application needed by KdybyModule\CliPresenter::injectConsole() not found. Did you register it in configuration file?"

So quick fix is putting this into 'application:' di config:
- scanComposer: FALSE

Maybe there would be nice some kind of ignore list?

ping @fprochazka

**Comment by fprochazka** [comment]
This should fix it, right? https://github.com/Kdyby/Console/commit/a15f4f36f4df63381f1fc272f56d970e9dc8de2c

**Comment by solcik** [comment]
:100: Indeed (pronounced like Teal'c)
