### ISSUE TITLE
RoutingExtension: unable to cache routes with dependencies

### ISSUE THREAD

**Issue by janedbal** [nette/application#64]
Any route of which generated method in SystemContainer contains ```$this``` is not cacheable because it leads to exception inside [eval](https://github.com/nette/application/blob/a12ded776ea0ac7ff238f9671947ca29f0957327/src/Bridges/ApplicationDI/RoutingExtension.php#L72), e.g.: ```Call to undefined method RoutingExtension::getService()```. Therefore any route with dependencies in constructor is not cacheable.

I don't know if this limitation can be eliminated, but at least, It would be nice to have some better error message. Or can it be eliminated?

For example [this](https://github.com/JanTvrdik/NetteCustomRouterExample/blob/ab12e98b142f87a38fb54929a85ed79c26f29b0a/app/router/CustomRouter.php#L21) and [this](https://github.com/dotblue/nette-webimages/blob/22e06e7263c2f936c6ae8a13c7e305fac7e74d3c/src/Extension.php#L63) route cannot be cached.

**Comment by fprochazka** [comment]
You may be able to hack your way around it using custom serialization, but it cannot be solved cleanly.

**Comment by dg** [comment]
Yes, this is the known limitation.
