### ISSUE TITLE
Leading colon in the destination breaks link generation using LinkGenerator

### ISSUE THREAD

**Issue by tobice** [nette/application#72]
We use modules in our application and sometimes we need to specify the destination absolutely using the leading colon. Something like `:Module:Presenter:action`. This works for normal link generation using `$presenter->link()` (or in templates) but the brand new `LinkGenerator` throws an `InvalidLinkException`  with the message `Presenter name must be alphanumeric string, ':Module:Presenter' is invalid`.

If I remove the leading colon, the `LinkGenerator` starts working, but now it's `$presenter->link()` that fails with an exception.

I might be doing something wrong but I'm pretty sure that the behavior should be consistent.

**Comment by EdaCZ** [comment]
I confirm this issue.
"...Presenter name must be alphanumeric string, ':Admin:PasswordReset' is invalid."

**Comment by fprochazka** [comment]
Isn't it because LinkGenerator doesn't know relative links and therefor it doesn't know absolute links? :)

**Comment by EdaCZ** [comment]
Seems logical, but how can I know, whether in _control param is Presenter or LinkGenerator?
Behaviour (from my point of view) should be the same (for absolute links) :-)

**Comment by tobice** [comment]
As a workaround I created my own link building service that corrects this behavior and I use it instead of the original `LinkGenerator`. Not sure if this is the proper way to go, though...

```php
<?php
namespace App\Misc;

use Nette\Object;

class LinkGenerator extends Object
{
	/** @var \Nette\Application\LinkGenerator */
	private $linkGenerator;

	public function __construct(\Nette\Application\LinkGenerator $linkGenerator)
	{
		$this->linkGenerator = $linkGenerator;
	}

	public function link($dest, array $params = array())
	{
		// Remove leading colong, currently broken in LinkGenerator
		$dest = preg_replace("/^:/", "", $dest);
		return $this->linkGenerator->link($dest, $params);
	}
}
```

**Comment by Achse** [comment]
I confirm this issue too. I guess it should work same way as `presenter->link`. This is confusing and really unexpected behaviour.

**Comment by martinsifra** [comment]
Ping

**Comment by lookyman** [comment]
Regardless of this issue, wouldn't it be best if Presenters (and Controls) used LinkGenerator to generate their links, instead of the way they do it now? I don't like the fact that this functionality is duplicated. I haven't looked at the code to see if it's even possible though, and I recon it would require some pretty major refactoring..

**Comment by martinsifra** [comment]
I just think there should be something to **fix** this issue **temporarily** because if you want to solve this problem correctly, it can take so long.

**Comment by Attanon** [comment]
Hi, what about the temporarily fix. Is it possible to merge?

**Comment by dg** [comment]
This is intentional behaviour described here https://github.com/nette/application/issues/72#issuecomment-84733218

**Comment by tobice** [comment]
I understand the argument but then it would make more sense to flip the behavior. Accept only destinations starting with a colon and throw an exception in other cases. Something like "Hey, I'm a LinkGenerator and I don't do relative links. Please specify the destination absolutely". That would be actually pretty helpful. The current message is confusing.

**Comment by Achse** [comment]
Internal implementation should not be a reason to unconsintance in API.

@tobice 
> Something like "Hey, I'm a LinkGenerator and I don't do relative links. Please specify the destination absolutely".

:+1:

**Comment by Majkl578** [comment]
> Something like "Hey, I'm a LinkGenerator and I don't do relative links.

Missing leading colon doesn't imply relative path. Much like with namespaces.

**Comment by hrach** [comment]
> Missing leading colon doesn't imply relative path. Much like with namespaces.

This is not much relevant comparison. In use statements you can never use relative namespace, though, in link creation you can use relative presenter/action path. The link pattern are exactly the same as the method names. IMO, the leading colon should be accepted with the warning - the same logic, as PHP has.

**Comment by dg** [comment]
Better warning is fine, but is shouldn't be calmly accepted.
