### ISSUE TITLE
PresenterCallbackFactory - duplicated creation of services

### ISSUE THREAD

**Issue by TomasVotruba** [nette/application#73]
I've just checked `PresenterFactoryCallback` call and how it works with registered presenters, and it looks like [presenter service is created, even if already exists](https://github.com/nette/application/blob/45f4efb155ccf172aeab134de20b4794164d4f97/src/Bridges/ApplicationDI/PresenterFactoryCallback.php#L59).

Maybe I'm missing something. If not, `getService` would be more suitable to call there.

**Comment by JanTvrdik** [comment]
That is a feature, you can not reuse presenter instance for handling multiple applications requests.

**Comment by TomasVotruba** [comment]
I see. Thanks for explaining. Do you have any use case apart testing?

**Comment by JanTvrdik** [comment]
use case for what?

**Comment by enumag** [comment]
@JanTvrdik use case where reusing the same presenter instance would cause problems

**Comment by TomasVotruba** [comment]
@enumag Exactly.

**Comment by dg** [comment]
It is how it works since first version of Nette.

**Comment by JanTvrdik** [comment]
A presenter may hold some state in its properties.

**Comment by TomasVotruba** [comment]
@JanTvrdik I mean some real use case example I might meet in practice. It would help me to connect theory with work.
