### ISSUE TITLE
HHVM causes malfunction of redirect(...) method of PresenterComponent since func_get_args returns arguments by references instead values

### ISSUE THREAD

**Issue by jeroneemou** [nette/application#77]
Since `PresenterComponent::redirect` function has optional parameter `$code`, following code: 
```php
if (!is_numeric($code)) { // first parameter is optional
	$args = $destination;
	$destination = $code;
	$code = NULL;
}


if (!is_array($args)) {
	$args = array_slice(func_get_args(), is_numeric($code) ? 2 : 1);
}
```

will cause difference between HHVM interpreter and PHP interpreter. Because `func_get_args` returns arguments by references instead values in HHVM.

**Example in HHVM**

calling:

```php
$this->redirect('Question:detail', 50);
```
will transfer parameters into:

	code        = NULL 
	destination = string(15) "Question:detail" 
	args        = array(1) { [0]=> string(15) "Question:detail" }

while call:

```php
$this->redirect('301', 'Question:detail', 50);
```

results in this:

	code        = string(3) "301" 
	destination = string(15) "Question:detail" 
	args        = array(1) { [0]=> int(61) }

----------

Difference between generated urls with route:
 
	new Route('admin/<presenter>/<action>/<id>',...)

is:

	admin/question/detail/Question%3Adetail - WRONG
	
vs:

	admin/question/detail/65 - CORRECT!

**Comment by JanTvrdik** [comment]
PHP 7 has [the very same issue](http://3v4l.org/c9rnA).

**Comment by dg** [comment]
IMHO ít is not returned by reference, but returns "current" values.
